name: nearby-users
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - pydantic
  - requests
  - streamlit
  - folium
  - pip
  - pip:
      - streamlit-folium
